config/routes.rb
Rails.application.routes.draw do
	root 'application#home'
	devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
	namespace :admin do
		resources :categories
		resources :food_recipes
		resources :users, only: [:index]
		root to: 'users#controlPanel'
	end
	get 'about', to:'application#about'
	get 'secrets', to: 'application#secrets'
	resources :categories, only:[:show]
	resources :food_recipes, only:[:index, :show, :update] do
		resources :comments
	end
	resources :users, only: [:edit, :update]
	get'/search', to:"application#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :food_recipes
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :food_recipe
	validates :content, presence: true
end

app/models/food_recipe.rb
class FoodRecipe < ActiveRecord::Base
	belongs_to :category
	has_many :likes
	has_many :users, :through => :likes
	has_many :comments
	has_many :users, :through => :comments

	#validates :name, :category_id, :method, :ingredients, :image, presence: true
	def category_name
		self.category.name
	end
	def self.search(keyword)
		FoodRecipe.where('name LIKE ?',"%#{keyword}%")
	end
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :food_recipe
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :likes
  has_many :food_recipes, :through => :likes
  has_many :comments
  has_many :food_recipes, :through=> :comments
  
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, 
  :omniauthable, :omniauth_providers => [:facebook]
  validates :username, presence: true, length: {maximum:14}, uniqueness: true
  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  		user.provider = auth.provider
  		user.uid = auth.uid
      user.username = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
  enum role: [:normal,:admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role 
    self.role ||= :normal
  end
  def guest?
    persisted?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	layout 'admin'
	before_action :find_category, only: [:show, :edit, :update, :destroy]
	def index
		@categories = Category.all
	end
	def new
		@category = Category.new
	end
	def create
		@category = Category.find_or_create_by(category_params)
		redirect_to admin_categories_path
	end
	def edit
	end
	def update
		if @category.update(category_params) then
			redirect_to admin_categories_path
		end
	end
	def destroy
		@category.destroy
		redirect_to admin_categories_path
	end
	private
	def category_params
		params.require(:category).permit(:name)
	end
	def find_category
		@category = Category.find(params[:id])
	end
end

app/controllers/admin/food_recipes_controller.rb
class Admin::FoodRecipesController < ApplicationController
	layout 'admin'
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]
	def index
		@recipes = FoodRecipe.all
	end
	def new
		@recipe = FoodRecipe.new
	end
	def create
		uploaded_io = params[:food_recipe][:image]
		File.open(Rails.root.join('public','uploads',uploaded_io.original_filename), "wb") do |file|
			file.write(uploaded_io.read)
		end
		@recipe = FoodRecipe.new(recipe_params)
		@recipe.image = uploaded_io.original_filename
		if @recipe.save
			redirect_to admin_food_recipes_path
		end
	end
	def edit
	end
	def update
		if @recipe.update(recipe_params) then
			redirect_to admin_food_recipe_path(@recipe)
		end
	end
	def destroy
		@recipe.destroy
		redirect_to admin_food_recipes_path
	end
	def show
	end
	private
	def recipe_params
		params.require(:food_recipe).permit(:name, :origin, :preparation_time, :description, :method, :number_of_persons, :image, :category_id, :ingredients)
	end
	def find_recipe
		@recipe = FoodRecipe.find(params[:id])
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	layout 'admin'
	def controlPanel
		if !current_user || current_user.try(:admin?) == false
			redirect_to root_path
		end
	end

	def settings
	end

	def myusers
		@myusers = User.select{ |u|
			!u.admin?
		}
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :authenticate_user!, if: :devise_controller?
	protect_from_forgery with: :exception
	layout Proc.new { |controller| 
		if controller.devise_controller?
			'devise'
		end
	}
	def home
	end
	def about
	end
	def secrets
	end
	def search
		@results = FoodRecipe.search(params[:search_keywords])
	end
	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
	end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		cat = Category.find(params[:id])
		@catRecipes = FoodRecipe.select{|recipe|
			recipe.category_name == cat.name
		}
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_comment, only: [:edit, :update, :destroy]
	before_action :find_recipe, only: [:create,:show, :edit, :update, :destroy]
	def create
		@comment = @recipe.comments.create(params_comment)
		@recipe.update(:numof_comments=>@recipe.numof_comments+1)
		respond_to do |format|
			format.html{redirect_to @recipe}
			format.js
		end
	end
	def edit
		respond_to do |format|
			format.html{redirect_to @recipe}
			format.js
		end
	end

	def update
		@comment.update(params_comment)
		respond_to do |format|
			format.html{redirect_to @recipe}
			format.js
		end
	end

	def destroy
		@comment.destroy
		@recipe.update(:numof_comments=>@recipe.numof_comments-1)
		respond_to do |format|
			format.html{redirect_to @recipe}
			format.js
		end
	end
	private
	def find_recipe
		@recipe = FoodRecipe.find(params[:food_recipe_id])
	end
	def find_comment
		@comment = Comment.find(params[:id])
	end

	def params_comment
		params.require(:comment).permit(:content, :food_recipe_id, :user_id)
	end
end

app/controllers/food_recipes_controller.rb
class FoodRecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :update]
	def index	
	end
	def show
	end
	#update number of likes
	def update
		if user_signed_in? then
			if Like.where("food_recipe_id =? and user_id = ?", @recipe.id, current_user.id).first !=nil
				Like.where("food_recipe_id =? and user_id = ?", @recipe.id, current_user.id).destroy_all
				@recipe.update(:numof_likes=>@recipe.numof_likes-1)
			else
				like = Like.create(:user_id=>current_user.id,:food_recipe_id=>@recipe.id)
				@recipe.update(:numof_likes=>@recipe.numof_likes+1)
			end
			respond_to do |format|
				format.html {redirect_to @recipe}
				format.js
			end
		end
	end
	private
	def find_recipe
		@recipe = FoodRecipe.find(params[:id])	
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def edit	
	end
	def update
		uploaded_io = params[:user][:profile_img]
		File.open(Rails.root.join('public','uploads',uploaded_io.original_filename), "wb") do |file|
			file.write(uploaded_io.read)
		end
		current_user.update(:username=>params[:user][:username], :email=>params[:user][:email], :profile_img=>uploaded_io.original_filename)
		redirect_to edit_user_path(current_user)
	end
	private
	def user_params
		params.require(:user).permit(:username, :email, :profile_img)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/food_recipes_helper.rb
module FoodRecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/_form.html.erb
<div id="title">
	<span>CATEGORY / FORMS</span>
	<%= image_tag('interface.png') %>
</div>

<div id="form-wrapper">
	<%= form_for([:admin, @category]) do |f|%>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<%= f.submit :class => "btn" %>
	<% end %>
	<a href="/admin/categories" class="btn"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Back
	</a>
</div>

app/views/admin/categories/index.html.erb
<div id="title">
	<span>CATEGORY / ITEMS</span>
	<%= image_tag('items.png') %>
</div>
<% @categories.each do |cat| %>
<div class="row">
	<div class="col-xs-2"><%= cat.name %></div>
	<div class="col-xs-4">
		<%= link_to 'Edit', edit_admin_category_path(cat) %>
		<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
		&emsp;&emsp;
		<%= link_to 'Delete',admin_category_path(cat), method: :delete, data:{confirm:'Are you sure ou want to delete this item?'}%>
		<i class="fa fa-times" aria-hidden="true"></i>
	</div>
</div>
<% end %>
<%= link_to 'New', new_admin_category_path, {:class=> "btn"} %>
<a href="/admin" class="btn"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Back To Panel
</a>

app/views/admin/categories/new.html.erb
<%= render 'form' %>

app/views/admin/food_recipes/_form.html.erb
<div id="title">
		<span>RECIPE / FORMS</span>
		<%= image_tag('interface.png') %>
	</div>
	<div id="form-wrapper">
		<%= form_for([:admin, @recipe]) do |f|%>
		<%= f.text_field :name, placeholder:"Name" %>
		<%= f.text_field :origin, placeholder:"Origin" %>
		<%= f.collection_select :category_id, Category.all, :id, :name %>
		<%= f.text_field :preparation_time, placeholder:"Preparation_time" %>
		<%= f.text_field :description, placeholder:"Description" %>
		<%= f.text_field :method, placeholder:"Method" %>
		<%= f.text_field :number_of_persons, placeholder:"Number_of_persons" %>
		<%= f.text_field :ingredients, placeholder:"Ingredients" %>
		<%= f.file_field :image %>
		<br>
		<%= f.submit :class => "btn" %>
		<% end %>
		<a href="/admin/food_recipes" class="btn"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Back
		</a>
	</div>
<!--
<select name="food_recipe[category_id]">
			<% Category.all.each do |cat| %>
			<option value="<%= cat.id %>"><%= cat.name %></option>
			<% end %>
</select>
		-->

app/views/admin/food_recipes/edit.html.erb
<%= render 'form' %>

app/views/admin/food_recipes/index.html.erb
<div id="title">
	<span>RECIPE / ITEMS</span>
	<%= image_tag('items.png') %>
</div>
<% @recipes.each do |recipe| %>
<div class="row">
	<div class="col-xs-3"><%= recipe.name %></div>
	<div class="col-xs-4">
		<%= link_to 'Edit', edit_admin_food_recipe_path(recipe) %>
		<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
		&emsp;&emsp;
		<%= link_to 'Delete',admin_food_recipe_path(recipe), method: :delete, data:{confirm:'Are you sure you want to delete this item?'}%>
		<i class="fa fa-times" aria-hidden="true"></i>
		&emsp;&emsp;
		<%= link_to 'view', admin_food_recipe_path(recipe) %>
		<i class="fa fa-eye" aria-hidden="true"></i>
	</div>
</div>
<% end %>
<%= link_to 'New', new_admin_food_recipe_path, {:class=> "btn"} %>
<a href="/admin" class="btn"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Back To Panel
</a>

app/views/admin/food_recipes/new.html.erb
<%= render 'form' %>

app/views/admin/food_recipes/show.html.erb
<div id="show-recipe">
	<h1><%= @recipe.name %></h1>
	<%= image_tag("/uploads/#{@recipe.image}") %>
	<p>Category:<%= @recipe.category_name %></p>
	<p>Origin: <%= @recipe.origin %></p>
	<p>Enough for: <%= @recipe.number_of_persons %></p>
	<p>Time required for preparation:<%= @recipe.preparation_time %></p>
	<p>Description: <%= @recipe.description %></p>
	<p>Ingredients: <%= @recipe.ingredients %></p>
	<p>Likes: <%= @recipe.numof_likes %></p>
	<p>Method<%= @recipe.method %></p>
	<%= link_to 'Back', admin_food_recipes_path, {:class=> "btn"} %>
</div>

app/views/admin/users/controlPanel.html.erb
<div class="row">
	<div class="col-xs-3 box text-center">
		<p>Total Users</p>
		<hr>
		<p class="num"><%= User.where("role!='admin'").length %></p>
	</div>
	<div class="col-xs-3 box text-center">
		<p>Total Comments</p>
		<hr>
		<p class="num">4</p>
	</div>
</div>

app/views/admin/users/index.html.erb
<div class="row">
	<%= @myusers.all.each do |u| %>
		<%= u.username %>
		<%= u.email %>
	<% end %>
</div>

app/views/application/home.html.erb
<header>
	<div class="row" id="first-row">
		<div class="col-xs-12" id="text">
			<h1>BEST RECIPES</h1>
			<p>You Will Find Here</p>
			<!-- search bar -->
			<%= form_tag("/search",method:"get") do %>
			<%= text_field_tag :search_keywords, params[:search_keywords] %>
			<span>
				<i class="fa fa-search" aria-hidden="true"></i>  
			</span>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 text-center">
			<h4 class="heading">RECENTLY ADDED</h4>
		</div>
	</div>
	<div class="row">
		<% FoodRecipe.order(created_at: :desc).each do |rec| %>
		<div class="col-sm-3 box text-center">
			<%= image_tag("/uploads/#{rec.image}", :class=>"image") %>
			<p><%= link_to "#{rec.name}",food_recipe_path(rec) %></p>
		</div>
		<% end %>
	</div>
	<div class="row">
		<div class="col-xs-12 text-center">
			<h4 class="heading">MOST POPULAR</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-3 box"></div>
		<div class="col-sm-3 box"></div>
		<div class="col-sm-3 box"></div>
		<div class="col-sm-3 box"></div>
	</div>
</header>
<!-- carousel 
	<div class="row">
		<div class="col-xs-7">
			<div id="myCarousel" class="carousel slide" data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
					<li data-target="#myCarousel" data-slide-to="1"></li>
					<li data-target="#myCarousel" data-slide-to="2"></li>
				</ol>

				<div class="carousel-inner">
					<div class="item active">
						<%= image_tag('pizza.jpg') %>
					</div>

					<div class="item">
						<%= image_tag('salad.jpg') %>
					</div>
					<div class="item">
						<%= image_tag('soup.jpeg') %>
					</div>
					<div class="item">
						<%= image_tag('cup-cakes.jpg') %>
					</div>

				</div>

				<a class="left carousel-control" href="#myCarousel" data-slide="prev">
					<i class="fa fa-chevron-left"></i>
					<span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#myCarousel" data-slide="next">
					<i class="fa fa-chevron-right"></i>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>

		<div class="col-xs-5">
			
		</div>
	</div>

-->

app/views/application/search.html.erb
<div class="container" id="search-container">
	<h4>We found <%= @results.length %> results for your search</h4>
	<div class="row">
		<% @results.each do |res| %>
		<div class="row">
			<div class="col-sm-4 col-xs-5">
				<%= image_tag("/uploads/#{res.image}") %>
			</div>
			<div class="col-xs-4" id="recName">
				<%= link_to "#{res.name}", food_recipe_path(res) %>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/categories/show.html.erb
<div class="container catRecipes-container">
	<div class="row">
		<% @catRecipes.each do |rec| %>
		<div class="col-sm-3 col-xs-6 item">
			<%= image_tag("/uploads/#{rec.image}", :class=>"image") %>
			<div class="middle">
				<%= link_to 'View', food_recipe_path(rec),{:class=> "text"} %>
			</div>
			<h4><%= rec.name %></h4>
			<p><%= rec.description %></p>
		</div>
		<% end %>
	</div>
</div>

app/views/comments/_edit.html.erb
<form action="/food_recipes/<%= @recipe.id%>/comments/<%= @comment.id %>" method="PUT" data-remote="true" id="edit_comment">
	<input type="text" value="<%= @comment.content%>" autofocus="true" name="comment[content]">
</form>

app/views/comments/create.js.erb
$('#recipe-comments').append('<% if current_user.profile_img != "user.png" %><%= image_tag("/uploads/#{current_user.profile_img}") %><% else %><%= image_tag('user.png') %><% end %> <%= @comment.content %>');
$('#comment_content').val("");
$('.row h4').text('<%= @recipe.numof_comments %> Comments');

app/views/comments/destroy.js.erb
$("#recipe-comments p").remove("#<%= @comment.id %>");
$('.row h4').text('<%= @recipe.numof_comments %> Comments');

app/views/comments/edit.js.erb
$('#<%= @comment.id %> .content').html("<%= j render 'edit' %>");

app/views/comments/update.js.erb
$('#<%= @comment.id %> form').remove("#edit_comment");
$('#<%= @comment.id %> .content').html('<%= @comment.content %>');

app/views/food_recipes/index.html.erb
<div class="container catRecipes-container">
	<div class="row">
		<% FoodRecipe.all.each do |rec| %>
		<div class="col-sm-4 col-xs-6 item">
			<%= image_tag("/uploads/#{rec.image}", :class=>"image") %>
			<div class="middle">
				<%= link_to 'View', food_recipe_path(rec),{:class=> "text"} %>
			</div>
			<h4><%= rec.name %></h4>
			<p><%= rec.description %></p>
		</div>
		<% end %>
	</div>
</div>

app/views/food_recipes/update.js.erb
$('#likes-div').html(<%= @recipe.numof_likes %>);

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Admin Dashboard</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'true' %>
	<link href="https://fonts.googleapis.com/css?family=Bad+Script" rel="stylesheet">
</head>
<body>
	<nav class="navbar" id="navbar">
		<div class="container-fluid">
			<div class="navbar-header">
				<span id="logo">WASFA</span>
				<i class="fa fa-bars"></i>
			</div>
			<div class="notice">
				<%= flash[:admin] %>
			</div>
			<div class="navbar-right">
				<ul class="nav navbar-nav">
					<li class="icon">
						<i class="fa fa-bell-o" aria-hidden="true"></i>
						<i class="fa fa-envelope-o" aria-hidden="true"></i>
					</li>
					<li class="dropdown text-center" id="dropdown">
						<span>Admin's Name</span>
						<span class="caret"></span>
						<span><%= image_tag('profile.jpg')%></span>
						<ul class="dropdown-menu" id="admin-menu">
							<li class="li">Settings</li>
							<li class="li">Profile</li>
							<li>logout</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<!-- sidebar -->
	<div id="sidebar">
		<div id="home">
			<i class="fa fa-home" aria-hidden="true"></i>
			<a href="/admin">Dashboard</a>
			<hr>
		</div>
		<div class="collapsed menu" data-toggle="collapse" data-target="#catlinks">
			<span>Category</span>
			<i class="fa fa-chevron-right" aria-hidden="true"></i>
		</div>
		<ul id="catlinks" class="collapse">
			<li><%= link_to 'All', admin_categories_path%></li>
			<li><%= link_to 'New', new_admin_category_path%></li>
		</ul>

		<div class="collapsed menu" data-toggle="collapse" data-target="#reclinks">
			<span>Recipe</span>
			<i class="fa fa-chevron-right" aria-hidden="true"></i>
		</div>
		<ul id="reclinks" class="collapse">
			<li><%= link_to 'All', admin_food_recipes_path%></li>
			<li><%= link_to 'New', new_admin_food_recipe_path%></li>
		</ul>

		<div class="collapsed menu" data-toggle="collapse" data-target="#sitelinks">
			<span>My Site</span>
			<i class="fa fa-chevron-right" aria-hidden="true"></i>
		</div>
		<ul id="sitelinks" class="collapse">
			<li><a href="/" target="_blank">Home page</a></li>
			<li><a href="/categories" target="_blank">Categories</a></li>
			<li><a href="food_recipes" target="_blank">Recipes</a></li>
			<li><a href="about" target="_blank">About</a></li>
			<li><a href="secrets" target="_blank">Kitchen Secrets</a></li>
		</ul>
	</div>
	<div class="container wrapper">
		<%= yield %>
	</div>
	<%= javascript_include_tag 'admin' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Wasfa</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'true' %>
	<link href="https://fonts.googleapis.com/css?family=Quicksand|Caveat|Josefin+Sans" rel="stylesheet">
	
</head>
<body>
	<div class="container">
		<nav class="row" id="upper-nav">
			<div class="col-xs-8" id="logo">
				<div class="row">
					<div class="col-xs-2">
						<span>Wasfa</span>
					</div>
					<div class="col-xs-1">
						<%= image_tag('broth.png') %>
					</div>
				</div>
			</div>
			<div class="col-xs-4" id="user">
				<% if user_signed_in? %>
				<% if current_user.profile_img != "user.png" %>
				<%= image_tag("/uploads/#{current_user.profile_img}") %>
				<% else %>
				<%= image_tag('user.png') %>
				<% end %>
				<%= current_user.username %>
				<i class="fa fa-cog" aria-hidden="true" id="gear"></i>
				<ul class="dropdown-menu" id="settings">
					<li><%= link_to "My Profile", edit_user_path(current_user) %></li>
					<li><%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
				</ul>
				<% else %>
				<%= link_to "Sign up", new_user_registration_path%>
				&nbsp;
				<span>|</span>&nbsp;
				<%= link_to "Login", new_user_session_path %>
				<% end %>
			</div>
		</nav>
		<!-- lower navigation -->
		<nav class="navbar" id="lower-nav">
			<div class="container-fluid">
				<div class="navbar-header">
					<button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-links">
						<i class="fa fa-bars"></i>
					</button>
				</div>
				<div class="collapse navbar-collapse" id="navbar-links">
					<ul class="nav navbar-nav col-xs-10">
						<li><%= link_to 'Home', root_path %></li>
						<li class="dropdown">
							<a href="categories">Categories
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<% Category.all.each do |cat| %>
								<li>
									<a href="/categories/<%= cat.id%>"><%= cat.name %>
									</a>
								</li>
								<% end %>
							</ul>
						</li>
						<li><%= link_to 'recipes', food_recipes_path %></li>
						<li><%= link_to 'About', about_path %></li>
						<li><%= link_to 'Kitchen Secrets', secrets_path %></li>
					</ul>
					<ul class="list-inline col-xs-2" id="social">
						<li>
							<a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="#"><i class="fa fa-instagram" aria-hidden="true"></i>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<%= yield %>
	</div>
	<footer>
		<div class="container">
			<div class="row text-center">
				<p>&copy;2017 copyrights.| Proudly created by Goory Hamed</p>
			</div>
		</div>
	</footer>
	<%= javascript_include_tag 'users' %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Wasfa - User Authentication</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track': 'true' %>
	<%= javascript_include_tag 'application' %>
</head>
<body>
	<div class="container devise-wrapper">
		<div class="row">
			<div class="col-xs-12">
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Wasfa</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'true' %>
	<link href="https://fonts.googleapis.com/css?family=Eagle+Lake|Caveat|Josefin+Sans" rel="stylesheet">
	
</head>
<body>
	<!-- header -->

	<div class="container profile">
		<header>
			<div class="row" id="first-r">
				<div class="col-xs-12">
					<i class="fa fa-cog" aria-hidden="true" id="gear"></i>
					<span>Account Settings</span>
				</div>
			</div>
			<div class="row">
				<%= form_for(current_user) do |f| %>
				<%= f.label :username %>
				<%= f.text_field :username, {:readonly=> true} %>
				<i class="fa fa-pencil edit-username" aria-hidden="true"></i>
			</div>
			<div class="row">
				<%= f.label :email %>
				<%= f.text_field :email, {:readonly=> true} %>
				<i class="fa fa-pencil edit-email" aria-hidden="true"></i>
			</div>
			<div class="row">
				<%= f.label :profile_img, "Profile Picture" %>
				<%= f.file_field :profile_img %>
				<%= f.submit "update" %>
				<% end %>
			</div>
		</div>
	</header>
</div>
<%= javascript_include_tag 'users' %>
</body>
</html>